In [1]:
print("Hello Wolrd!")

Hello Wolrd!


In [2]:
import numpy as np

In [68]:
# Creating Arrays
a = np.array([[3,2], [3,6]])
b = np.array([[1,2],[4,5]])

In [69]:
print(a.shape) # dimension of array

(2, 2)


In [70]:
b.reshape(4,1)

array([[1],
       [2],
       [4],
       [5]])

In [71]:
# Math Operations
print(np.sum(a))
print(np.mean(b))
print(np.std(a)) 

14
3.0
1.5


In [72]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(np.dot(A, B))      # Matrix multiplication

[[ 4  4]
 [10  8]]


In [73]:
print(a.ndim) # not a function call
#just an integer attribute of array
print(a.size)

2
4


In [74]:
# Array Slicing
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr[0, 2]                                 # 30
arr[:, 1]                                 # Column 1 → [20, 50]
arr[1, :]                                 # Row 1 → [40, 50, 60]

array([40, 50, 60])

In [75]:
# Arithmetic operation
print(a+b)
print(a**2)
np.sqrt(b)

[[ 4  4]
 [ 7 11]]
[[ 9  4]
 [ 9 36]]


array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

In [76]:
# Aggregate Function
print(np.mean(a))                                # Mean
print(np.median(a))                              # Median
print(np.std(a))                                 # Standard deviation
print(np.var(a))                                 # Variance
print(np.sum(a))                                 # Sum
print(np.min(a))
print(np.max(a))                      # Min and Max
print(np.percentile(a, 75))                      # 75th percentile


3.5
3.0
1.5
2.25
14
2
6
3.75


In [77]:
A = np.array([[1,2,3],[5,6,7],[15,6,7]])
B = np.array([[11,12,13],[14,15,16],[5,6,7]])

In [78]:
# Matrix Operations
print(np.dot(A, B))
print(A@B) # works same as dot product, just another operator
print(np.transpose(A))
print(np.linalg.inv(A))
print(np.linalg.eig(A))
print(np.linalg.det(B))

[[ 54  60  66]
 [174 192 210]
 [284 312 340]]
[[ 54  60  66]
 [174 192 210]
 [284 312 340]]
[[ 1  5 15]
 [ 2  6  6]
 [ 3  7  7]]
[[ 0.   -0.1   0.1 ]
 [-1.75  0.95 -0.2 ]
 [ 1.5  -0.6   0.1 ]]
EigResult(eigenvalues=array([16.41076916, -3.17778814,  0.76701899]), eigenvectors=array([[-0.22679774, -0.3924156 ,  0.10562372],
       [-0.6161052 , -0.41303629, -0.83116235],
       [-0.75430575,  0.82183394,  0.54590546]]))
-1.5987211554602308e-14


In [79]:
# Handling Missing or Invalid Data
arr = np.array([1,2,3,np.nan])
print(np.isnan(arr))
print(np.nanmean(arr)) # mean ignoring nan
arr[~np.isnan(arr)] #Array without nan

[False False False  True]
2.0


array([1., 2., 3.])

## 🎯 `np.random.seed(0)` – What Does It Do?

`np.random.seed(0)` sets the **starting point** for NumPy's random number generator, so you get the **same random numbers every time** you run your code.

---

### 🔍 Why Use It?

In ML and data science, **reproducibility** is important. When you:

* Split data randomly
* Shuffle a dataset
* Generate random weights

...you may want to reproduce the **same results** every time (especially for debugging or sharing results).

---

### 🧪 Example Without `seed`:

```python
import numpy as np

print(np.random.rand(3))
# Output: Different every time
```

### 🧪 Example With `np.random.seed(0)`:

```python
import numpy as np

np.random.seed(0)
print(np.random.rand(3))
# Output: [0.5488135  0.71518937 0.60276338]
```

Even if you run this 100 times, the output is the **same**.

---

### ⚠️ Notes:

* You can use **any number** as the seed (`np.random.seed(42)` is common).
* Use it **once** at the beginning of your code—not before every random operation.
* It doesn’t affect `random` module in Python or other libraries like `torch`.

---

### ✅ In ML Code:

```python
np.random.seed(0)
X = np.random.rand(100, 5)  # Always same features


In [80]:
np.random.seed(0)

## 📘 `np.random.randint(1, 10, size=(2, 2))`

This function generates a **2x2 NumPy array** of **random integers** between 1 (inclusive) and 10 (exclusive).

---

### 🧩 Function Signature:

```python
np.random.randint(low, high=None, size=None, dtype=int)
```

---

### 🔍 Parameter Breakdown:

| Parameter | Description                                                                                   |
| --------- | --------------------------------------------------------------------------------------------- |
| `low`     | **Lower bound (inclusive)** — the smallest integer that can appear in the output              |
| `high`    | **Upper bound (exclusive)** — the largest number the output can go up to, **but not include** |
| `size`    | Shape of the output array — `(rows, columns)`                                                 |
| `dtype`   | Data type of output, default is `int`                                                         |

---

### 💡 Examples:

```python
np.random.randint(0, 5, size=4)
# Output: 1D array with 4 random numbers from 0 to 4

np.random.randint(10, size=(3, 1))
# Output: 3x1 array with numbers from 0 to 9
```

If you only pass **one number**, it becomes the **high**, and `low` defaults to 0:

```python
np.random.randint(5)  # Same as np.random.randint(0, 5)

In [81]:
print(np.random.rand(2)) #if we run this just after np.random.seed(0) then output is always same
print(np.random.rand(2,3,4)) #else answer is always different
print(np.random.randn(100)) #normal distribution of random numbers
print(np.random.randint(3,10, size = (6,7)))

[0.5488135  0.71518937]
[[[0.60276338 0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276 0.38344152]
  [0.79172504 0.52889492 0.56804456 0.92559664]]

 [[0.07103606 0.0871293  0.0202184  0.83261985]
  [0.77815675 0.87001215 0.97861834 0.79915856]
  [0.46147936 0.78052918 0.11827443 0.63992102]]]
[-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462 -1.45436567
  0.04575852 -0.18718385  1.53277921  1.46935877  0.15494743  0.37816252
 -0.88778575 -1.98079647 -0.34791215  0.15634897  1.23029068  1.20237985
 -0.38732682 -0.30230275 -1.04855297 -1.42001794 -1.70627019  1.9507754
 -0.50965218 -0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028
 -0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223  0.42833187
  0.06651722  0.3024719  -0.63432209 -0.36274117 -0.67246045 -0.35955316
 -0.81314628 -1.7262826   0.17742614 -0.40178094 -1.63019835  0.46278226
 -0.90729836  0.0519454   0.72909056  0.12898291  1.13940068 -1.23482582
  0.40234164 -0.68481009 -0.

## 🔹 `np.clip(a, 0, 2)`

### 🔧 Purpose:

**Clip (limit)** the values in the array `a` so that:

* Anything **less than 0** becomes 0
* Anything **greater than 2** becomes 2
* Values **in between remain unchanged**

### 📘 Syntax:

```python
np.clip(array, min_value, max_value)
```

### 🧪 Example:

```python
import numpy as np

a = np.array([-3, 0, 1, 2, 3, 5])
np.clip(a, 0, 2)
```

🔽 Output:

```python
array([0, 0, 1, 2, 2, 2])
```

### ✅ Use Case:

Useful for normalization, image pixel bounding (0–255), or keeping outputs within a range.

---

## 🔹 `np.where(a > 1, 1, 0)`

### 🔧 Purpose:

Conditional replacement in array `a`.

### 📘 Syntax:

```python
np.where(condition, value_if_true, value_if_false)
```

### 🧪 Example:

```python
a = np.array([0, 1, 2, 3, 1])
np.where(a > 1, 1, 0)
```

🔽 Output:

```python
array([0, 0, 1, 1, 0])
```

* For each element in `a`, if it's greater than 1 → replace with `1`
* Else → replace with `0`

### ✅ Use Case:

* Binary encoding
* Label transformation
* Creating masks (like turning scores > threshold into 1)

---

### 🧠 Summary Table

| Function              | Purpose                         | Example Output  |
| --------------------- | ------------------------------- | --------------- |
| `np.clip(a, 0, 2)`    | Limit values between 0 and 2    | `[0 0 1 2 2 2]` |
| `np.where(a>1, 1, 0)` | Set values >1 to 1, others to 0 | `[0 0 1 1 0]`   |

In [82]:
print(np.unique([1, 1, 2, 3]))                   # [1 2 3]
print(np.sort(a))                              # Sort
print(np.argsort(a))                             # Indices that would sort
print(np.clip(a, 0, 2))                          # Force values between 0 and 2
print(np.where(a > 1, 1, 0))                     # Conditional replacement

[1 2 3]
[[2 3]
 [3 6]]
[[1 0]
 [0 1]]
[[2 2]
 [2 2]]
[[1 1]
 [1 1]]
